# Generated by Django 4.2.27 on 2026-01-23 11:01

from django.db import migrations, models
import django.db.models.deletion


def populate_roles(apps, schema_editor):
    """Populate roles table before migrating user roles"""
    Role = apps.get_model("common", "Role")
    
    role_data = [
        {"code": "superadmin", "name": "Super Admin", "description": "Platform owner with full system access"},
        {"code": "admin", "name": "Admin", "description": "Organization administrator"},
        {"code": "hr", "name": "HR", "description": "Human Resources role"},
        {"code": "assignee", "name": "Assignee", "description": "Sales/Execution role"}
    ]
    
    for data in role_data:
        Role.objects.get_or_create(code=data["code"], defaults=data)


def migrate_user_roles_to_fk(apps, schema_editor):
    """Migrate user role strings to role foreign keys using raw SQL"""
    db_alias = schema_editor.connection.alias
    
    # First, populate roles if not already done
    populate_roles(apps, schema_editor)
    
    # Use raw SQL to update user roles
    with schema_editor.connection.cursor() as cursor:
        # Update users: set role_id based on role string value
        cursor.execute("""
            UPDATE users 
            SET role_id = (
                SELECT id FROM roles 
                WHERE roles.code = users.role::text
            )
            WHERE users.role IS NOT NULL 
            AND EXISTS (
                SELECT 1 FROM roles 
                WHERE roles.code = users.role::text
            )
        """)


def reverse_migrate_user_roles(apps, schema_editor):
    """Reverse migration - convert FKs back to strings"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE users 
            SET role = (
                SELECT code FROM roles 
                WHERE roles.id = users.role_id
            )
            WHERE users.role_id IS NOT NULL
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_roles, migrations.RunPython.noop),
        # Add temporary role_id field
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.IntegerField(null=True, blank=True),
        ),
        # Migrate data from role (string) to role_id (FK)
        migrations.RunPython(migrate_user_roles_to_fk, reverse_migrate_user_roles),
        # Remove old role CharField
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        # Rename role_id to role and make it a proper FK
        migrations.RenameField(
            model_name='user',
            old_name='role_id',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='common.role'),
        ),
    ]
